#server:
#  port: 14258
#
#spring:
#  datasource:
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: password
#    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update

