server:
  port: 14258
spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
  jpa:
    show-sql: true

  hibernate:
    ddl-auto: update
  #mybatis:
  #type-aliases-package: com.whisper.shop.entity
  #mapper-locations: classpath:mapper/*Mapper.xml